default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 25
  username: admin
  password: password

development:
  <<: *default
  database: jizhaku_development

test:
  <<: *default
  database: jizhaku_test

production:
  <<: *default
  database: jizhaku_production
  username: jizhaku
  password: <%= ENV['JIZHAKU_DATABASE_PASSWORD'] %>
